# Docker Compose override para desenvolvimento local
# Este arquivo é usado automaticamente junto com compose.yaml em desenvolvimento

services:
  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AzureStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - AzureStorage__ContainerName=documentos-dev
    depends_on:
      - azurite

  # Emulador do Azure Storage para desenvolvimento
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service  
      - "10002:10002"  # Table service
    volumes:
      - azurite_data:/data
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0

volumes:
  azurite_data:
