CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" varchar(100) NOT NULL,
    "Email" varchar(100) NOT NULL,
    "SenhaHash" text NOT NULL,
    "Papel" varchar(20) NOT NULL,
    "EhVerificado" boolean NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

CREATE TABLE "CartasConsorcio" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VendedorId" integer NOT NULL,
    "ValorCredito" numeric(18,2) NOT NULL,
    "ValorEntrada" numeric(18,2) NOT NULL,
    "ParcelasPagas" integer NOT NULL,
    "ParcelasTotais" integer NOT NULL,
    "ValorParcela" numeric(18,2) NOT NULL,
    "Status" varchar(20) NOT NULL,
    "TipoBem" varchar(50) NOT NULL,
    "Descricao" text,
    "CriadoEm" timestamp with time zone NOT NULL,
    "EhVerificado" boolean NOT NULL,
    CONSTRAINT "PK_CartasConsorcio" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CartasConsorcio_Usuarios_VendedorId" FOREIGN KEY ("VendedorId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CartasConsorcio_Status" ON "CartasConsorcio" ("Status");

CREATE INDEX "IX_CartasConsorcio_TipoBem" ON "CartasConsorcio" ("TipoBem");

CREATE INDEX "IX_CartasConsorcio_VendedorId" ON "CartasConsorcio" ("VendedorId");

CREATE UNIQUE INDEX "IX_Usuarios_Email" ON "Usuarios" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250807165722_Initial', '9.0.0');

COMMIT;

